services:
  tasktracker:
    image: ${DOCKER_REGISTRY-}tasktracker
    container_name: tasktracker.api
    build:
      context: ./TaskTracker
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000                  
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - /mnt/c/Users/User/local-secrets/UserSecrets:/root/.microsoft/usersecrets
      - /mnt/c/Users/User/local-secrets/Https:/root/.microsoft/https

  tasktracker.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tasktracker_database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrong!Passw0rd
      - MSSQL_DATABASE=TaskTrackerDb
    volumes:
      - my_db:/var/opt/mssql
    ports:
      - "1433:1433"

  products.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  my_db: