version: '3.8'

services:
  tasktracker:
    image: ${DOCKER_REGISTRY-}tasktracker
    container_name: tasktracker.api
    build:
      context: ./TaskTracker
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

  tasktracker.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tasktracker_database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrong!Passw0rd
      - MSSQL_DATABASE=TaskTrackerDb
    volumes:
      - my_db:/var/opt/mssql
    ports:
      - "1433:1433"

volumes:
  my_db: