version: '3.4'

services:
  tasktracker:
    image: ${DOCKER_REGISTRY-}tasktracker
    container_name: tasktracker.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  tasktracker.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tasktracker_database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrong!Passw0rd
      - MSSQL_DATABASE=TaskTrackerDb
    volumes:
      - my_db:/var/opt/mssql
    ports:
      - "1433:1433"

volumes:
  my_db: